### ISSUE TITLE
Odometry drifting in height - This results in a curved map

### ISSUE THREAD

**Issue by julianst** [laboshinl/loam_velodyne#62]
As also observed by @CansenJIANG @TopGunSnake @kamiyuanyang @nikitaporje the resulting map and position is drifting in Z-direction, which results in a bended map:
![loam1](https://user-images.githubusercontent.com/4341481/40135527-dd508e88-5945-11e8-8cf2-8ce88281a8b2.PNG)
![loam2](https://user-images.githubusercontent.com/4341481/40135535-e25a9374-5945-11e8-9019-701aa2f38ae3.PNG)

**Comment by julianst** [comment]
I was able to confirm tis issue with the VLP 16 sample pcaps 2014-11-10-10-36-54_Velodyne-VLP_10Hz-County Fair.pcap and 2014-11-10-10-48-31_Velodyne-VLP_20Hz_Hecker Pass.pcap from https://midas3.kitware.com/midas/folder/12979 as well as live VLP 16 data running Ubuntu 16.04 LTS and ROS kinetic.

Is there anyone having the same issue?

**Comment by ashnarayan13** [comment]
Hi, 

What was the fix for this problem? 
When I run loam with a direct LiDAR stream, I get this drift as well. This is more apparent when the sensor is stationary. 

Thanks

**Comment by kongcheng08** [comment]
I have the same problem  with vlp16 LiDAR when running outdoor environment , Now have any solution ?

**Comment by zr2539168** [comment]
I face the same problem, did you fix it? Thanks

**Comment by notmoonshine** [comment]
I have the same problem

**Comment by mistercherryy** [comment]
Anyone solved this issue or has a clue how to solve it? I am suffering the same issue.
