### ISSUE TITLE
VLP-16 rosbag example link is broken

### ISSUE THREAD

**Issue by tigerk0430** [laboshinl/loam_velodyne#74]
in Readme.MD VLP16 rosbag

**Comment by Osborn28** [comment]
rosbag: http://www.frc.ri.cmu.edu/~jizhang03/Datasets/
pcap: https://midas3.kitware.com/midas/folder/12979

**Comment by tigerk0430** [comment]
thank you :-)

**Comment by YuxinZheng0507** [comment]
rosbag: http://www.frc.ri.cmu.edu/~jizhang03/Datasets/
pcap: https://midas3.kitware.com/midas/folder/12979

These two links are broken now

**Comment by LongruiDong** [comment]
rosbag: http://www.frc.ri.cmu.edu/~jizhang03/Datasets/
This link is broken now

**Comment by Delmainn** [comment]
Is there any working link available?
