### ISSUE TITLE
void TransformMaintenance::transformAssociateToMap() <- what's happening.

### ISSUE THREAD

**Issue by MontyTHall** [laboshinl/loam_velodyne#81]
Subject says it all.  I'm curious what's happening here.

Thanks,

M

**Comment by narutojxl** [comment]
Hi @MontyTHall , did you have solve your problem, i have the same problem. 
Hi @laboshinl , did you figure out some docs about this function [ BasicTransformMaintenance::transformAssociateToMap()](https://github.com/laboshinl/loam_velodyne/blob/a06980a3e1619ddc8d34b188ac359a1ad8722a1d/src/lib/BasicTransformMaintenance.cpp#L83)
