### ISSUE TITLE
Dynamic environment

### ISSUE THREAD

**Issue by jonla1** [laboshinl/loam_velodyne#95]
Hi,
does anyone tested the algorithm in an dynamic environment? As far as I see it: Dynamic objects are causing trails in the point cloud map therefore the mapping might be off if the algorithm is run long enough in the presence of dynamic objects.
Can anyone confirm this?

**Comment by Jackey-Huo** [comment]
Yep, I have tried. It's true that loam will add points of dynamic objects into the map. But it never recognizes dynamic objects as feature points or feature surface.

So the conclusion is, regard to the localization part, it's capable to work in a dynamic environment.

(BTW, most dynamic object in my experiment is pedestrian)

**Comment by jonla1** [comment]
Thanks a lot for your answer.
